from django.db import models


class ArchiveConversationsJobStatus(models.TextChoices):
    PENDING = "PENDING"
    PROCESSING_MESSAGES = "PROCESSING_MESSAGES"
    MESSAGES_PROCESSED = "MESSAGES_PROCESSED"
    UPLOADING_MESSAGES_FILE = "UPLOADING_MESSAGES_FILE"
    MESSAGES_FILE_UPLOADED = "MESSAGES_FILE_UPLOADED"
    DELETING_MESSAGES_FROM_DB = "DELETING_MESSAGES_FROM_DB"
    MESSAGES_DELETED_FROM_DB = "MESSAGES_DELETED_FROM_DB"
    FINISHED = "FINISHED"
    FAILED = "FAILED"
