# Generated by Django 4.1.2 on 2025-05-08 19:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeaturePrompt",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="Modified on"),
                ),
                ("feature", models.CharField(max_length=255, verbose_name="Feature")),
                ("model", models.CharField(max_length=255, verbose_name="Model")),
                (
                    "settings",
                    models.JSONField(blank=True, null=True, verbose_name="Settings"),
                ),
                ("prompt", models.TextField(verbose_name="Prompt")),
                ("version", models.IntegerField(default=1, verbose_name="Version")),
            ],
            options={
                "verbose_name": "AI Feature Prompt",
                "verbose_name_plural": "AI Feature Prompts",
                "unique_together": {("feature", "version")},
            },
        ),
    ]
