# Generated by Django 4.0.4 on 2026-05-20 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featureprompt',
            options={'verbose_name': 'AI feature prompt', 'verbose_name_plural': 'AI feature prompts'},
        ),
    ]
