# Generated by Django 4.0.5 on 2022-08-23 13:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('email', models.EmailField(help_text='User email', max_length=254, unique=True, verbose_name='email')),
                ('status', models.CharField(blank=True, max_length=30, verbose_name='status')),
                ('custom_fields', models.JSONField(blank=True, null=True, verbose_name='custom fields')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
