# Generated by Django 4.0.5 on 2022-08-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='custom_fields',
            field=models.JSONField(blank=True, null=True, verbose_name='custom fields'),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(blank=True, max_length=30, verbose_name='status'),
        ),
    ]
