# Generated by Django 4.0.5 on 2022-09-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='phone'),
        ),
    ]
