# Generated by Django 4.0.5 on 2022-09-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='external_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='External ID'),
        ),
    ]
