# Generated by Django 4.1.2 on 2023-01-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_alter_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="first name"
            ),
        ),
    ]
