# Generated by Django 4.1.2 on 2025-05-27 19:57

from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("contacts", "0005_alter_contact_name"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="contact",
            index=models.Index(
                fields=["external_id"],
                name="contact_external_id_idx",
                condition=models.Q(external_id__isnull=False),
            ),
        ),
    ]
