# Generated by Django 4.1.2 on 2025-06-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0006_alter_contact_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="imported_history_url",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Imported History URL"
            ),
        ),
    ]
