# Generated by Django 4.1.2 on 2025-06-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0007_contact_imported_history_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="imported_history_url",
            field=models.TextField(
                blank=True, default="", verbose_name="Imported History URL"
            ),
        ),
    ]
