# Generated by Django 4.0.10 on 2025-08-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_contact_imported_history_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='imported_history_url',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Imported History URL'),
        ),
    ]
