# Generated by Django 4.0.4 on 2026-01-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_add_index_to_contact_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('external_id',), name='unique_contact_external_id'),
        ),
    ]
