# Generated by Django 4.0.4 on 2026-07-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0014_add_document_email_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="imported_history_url",
            field=models.TextField(
                blank=True, default="", verbose_name="Imported history URL"
            ),
        ),
    ]
