# Generated by Django 4.1.2 on 2024-08-13 18:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0019_flowstart_contact_data"),
        ("feature_version", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureVersion",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="Modified on"),
                ),
                (
                    "feature_version",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="feature version id"
                    ),
                ),
                (
                    "sectors",
                    models.JSONField(
                        blank=True, null=True, verbose_name="sectors list"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_versions",
                        to="projects.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
