# Generated by Django 4.0.4 on 2026-07-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_version', '0003_integratedfeature_delete_featureversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integratedfeature',
            name='current_version',
            field=models.JSONField(blank=True, null=True, verbose_name='department list'),
        ),
    ]
