# Generated by Django 4.0.4 on 2022-06-10 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                ("rooms_limit", models.IntegerField(verbose_name="Rooms limit")),
                ("work_start", models.IntegerField(verbose_name="work start")),
                ("work_end", models.IntegerField(verbose_name="work end")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                        verbose_name="sectors",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.CreateModel(
            name="SectorPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.PositiveIntegerField(
                        choices=[(0, "not set"), (1, "admin"), (2, "manager")],
                        default=0,
                        verbose_name="role",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sectors.sector",
                        verbose_name="Sector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Permission",
                "verbose_name_plural": "Project Permissions",
            },
        ),
    ]
