# Generated by Django 4.0.5 on 2022-08-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectorauthorization',
            old_name='user',
            new_name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='sectorauthorization',
            unique_together={('permission', 'sector')},
        ),
    ]
