# Generated by Django 4.0.5 on 2022-07-26 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_alter_projectpermission_project_and_more'),
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('role', models.PositiveIntegerField(choices=[(0, 'not set'), (1, 'admin'), (2, 'manager')], default=1, verbose_name='role')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='sectors.sector', to_field='uuid', verbose_name='Sector')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_authorizations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Sector Authorization',
                'verbose_name_plural': 'Sector Authorizations',
                'unique_together': {('user', 'sector')},
            },
        ),
        migrations.CreateModel(
            name='SectorTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='sectors.sector', to_field='uuid', verbose_name='Sector')),
            ],
            options={
                'verbose_name': 'Sector Tag',
                'verbose_name_plural': 'Sector Tags',
            },
        ),
        migrations.AddField(
            model_name='sector',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is deleted?'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='projects.project', to_field='uuid', verbose_name='sectors'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='rooms_limit',
            field=models.PositiveIntegerField(verbose_name='Rooms limit per employee'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='work_end',
            field=models.TimeField(verbose_name='work end'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='work_start',
            field=models.TimeField(verbose_name='work start'),
        ),
        migrations.DeleteModel(
            name='SectorPermission',
        ),
    ]
