# Generated by Django 4.0.5 on 2022-09-20 17:50

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sector',
            constraint=models.CheckConstraint(check=models.Q(('work_end__gt', django.db.models.expressions.F('work_start'))), name='wordend_greater_than_workstart_check'),
        ),
        migrations.AddConstraint(
            model_name='sector',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_sector_name'),
        ),
        migrations.AddConstraint(
            model_name='sector',
            constraint=models.CheckConstraint(check=models.Q(('rooms_limit__gt', 0)), name='rooms_limit_greater_than_zero'),
        ),
        migrations.AddConstraint(
            model_name='sectortag',
            constraint=models.UniqueConstraint(fields=('sector', 'name'), name='unique_tag_name'),
        ),
    ]
