# Generated by Django 4.0.5 on 2022-09-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0002_sector_wordend_greater_than_workstart_check_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sectorauthorization',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='sectorauthorization',
            constraint=models.UniqueConstraint(fields=('sector', 'permission'), name='unique_sector_auth'),
        ),
    ]
