# Generated by Django 4.1.2 on 2022-12-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sectors", "0003_alter_sectorauthorization_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="can_trigger_flows",
            field=models.BooleanField(
                default=False,
                help_text="Is it possible to trigger flows(weni flows integration) from this sector?",
                verbose_name="Can trigger flows?",
            ),
        ),
    ]
