# Generated by Django 4.1.2 on 2023-06-07 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sectors", "0004_sector_can_trigger_flows"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sector",
            name="rooms_limit_greater_than_zero",
        ),
    ]
