# Generated by Django 4.1.2 on 2023-07-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sectors", "0005_remove_sector_rooms_limit_greater_than_zero"),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="can_edit_custom_fields",
            field=models.BooleanField(
                default=False, verbose_name="Can edit custom fields?"
            ),
        ),
    ]
