# Generated by Django 4.1.2 on 2023-07-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sectors", "0006_sector_open_offline"),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="sign_messages",
            field=models.BooleanField(default=False, verbose_name="Sign messages?"),
        ),
    ]
