# Generated by Django 4.1.2 on 2023-07-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sectors", "0007_sector_sign_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="can_edit_custom_fields",
            field=models.BooleanField(
                default=False, verbose_name="Can edit custom fields?"
            ),
        ),
    ]
