# Generated by Django 4.1.2 on 2025-02-10 20:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_project_org"),
        ("sectors", "0010_alter_sectortag_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupSector",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="Modified on"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="is deleted?"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                (
                    "rooms_limit",
                    models.PositiveIntegerField(
                        verbose_name="Rooms limit per employee"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_sectors",
                        to="projects.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Sector",
                "verbose_name_plural": "Group Sectors",
            },
        ),
        migrations.CreateModel(
            name="SectorGroupSector",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="Modified on"),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sector_group_sectors",
                        to="sectors.sector",
                    ),
                ),
                (
                    "sector_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sector_group_sectors",
                        to="sectors.groupsector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sector Group Sector",
                "verbose_name_plural": "Sector Group Sectors",
            },
        ),
        migrations.AddField(
            model_name="groupsector",
            name="sectors",
            field=models.ManyToManyField(
                blank=True,
                related_name="group_sectors",
                through="sectors.SectorGroupSector",
                to="sectors.sector",
            ),
        ),
        migrations.AddConstraint(
            model_name="sectorgroupsector",
            constraint=models.UniqueConstraint(
                fields=("sector_group", "sector"), name="unique_sector_group_sector"
            ),
        ),
    ]
