# Generated by Django 4.1.2 on 2025-02-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sectors", "0010_alter_sectortag_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="integration_config",
            field=models.JSONField(
                blank=True,
                null=True,
                verbose_name="config to use in project integration",
            ),
        ),
    ]
