# Generated by Django 4.1.2 on 2025-02-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sectors", "0011_sector_integration_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sector",
            name="integration_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                null=True,
                verbose_name="config to use in project integration",
            ),
        ),
    ]
