# Generated by Django 4.1.2 on 2025-02-11 02:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_project_org"),
        ("sectors", "0011_groupsector_sectorgroupsector_groupsector_sectors_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupSectorAuthorization",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="Modified on"),
                ),
                (
                    "role",
                    models.PositiveIntegerField(
                        choices=[(0, "not set"), (1, "manager"), (2, "agent")],
                        default=0,
                        verbose_name="role",
                    ),
                ),
                (
                    "group_sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_sector_authorizations",
                        to="sectors.groupsector",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_sector_authorizations",
                        to="projects.projectpermission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Sector Authorization",
                "verbose_name_plural": "Group Sector Authorizations",
            },
        ),
        migrations.AddConstraint(
            model_name="groupsectorauthorization",
            constraint=models.UniqueConstraint(
                fields=("group_sector", "permission"), name="unique_group_sector_auth"
            ),
        ),
    ]
