# Generated by Django 4.1.2 on 2025-02-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sectors", "0012_groupsectorauthorization_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="groupsectorauthorization",
            name="unique_group_sector_auth",
        ),
        migrations.AddConstraint(
            model_name="groupsectorauthorization",
            constraint=models.UniqueConstraint(
                fields=("group_sector", "permission", "role"),
                name="unique_group_sector_auth",
            ),
        ),
    ]
