# Generated by Django 4.1.2 on 2025-07-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sectors",
            "0013_remove_groupsectorauthorization_unique_group_sector_auth_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="working_day",
            field=models.JSONField(blank=True, null=True, verbose_name="working_day"),
        ),
    ]
