# Generated by Django 4.0.10 on 2025-08-08 18:06

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0014_sector_working_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorHoliday',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted?')),
                ('date', models.DateField(verbose_name='Date')),
                ('day_type', models.CharField(choices=[('closed', 'Closed'), ('custom_hours', 'Custom Hours')], default='closed', max_length=20, verbose_name='Day Type')),
                ('start_time', models.TimeField(blank=True, help_text='Leave empty if day is closed', null=True, verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, help_text='Leave empty if day is closed', null=True, verbose_name='End Time')),
                ('description', models.CharField(blank=True, help_text='Holiday name or reason for special hours', max_length=255, verbose_name='Description')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='sectors.sector', verbose_name='Sector')),
            ],
            options={
                'verbose_name': 'Sector Holiday',
                'verbose_name_plural': 'Sector Holidays',
                'ordering': ['date'],
            },
        ),
        migrations.AddIndex(
            model_name='sectorholiday',
            index=models.Index(fields=['sector', 'date'], name='idx_sector_holiday'),
        ),
        migrations.AddConstraint(
            model_name='sectorholiday',
            constraint=models.UniqueConstraint(fields=('sector', 'date'), name='unique_sector_holiday'),
        ),
        migrations.AddConstraint(
            model_name='sectorholiday',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('day_type', 'closed'), ('end_time__isnull', True), ('start_time__isnull', True)), models.Q(('day_type', 'custom_hours'), ('end_time__isnull', False), ('start_time__isnull', False)), _connector='OR')), name='valid_holiday_times'),
        ),
        migrations.AddConstraint(
            model_name='sectorholiday',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', django.db.models.expressions.F('start_time')), ('start_time__isnull', True), _connector='OR'), name='holiday_end_greater_than_start'),
        ),
    ]
