# Generated by Django 4.0.10 on 2025-08-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0015_sectorholiday_sectorholiday_idx_sector_holiday_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sector',
            name='wordend_greater_than_workstart_check',
        ),
        migrations.RemoveConstraint(
            model_name='sector',
            name='unique_sector_name',
        ),
        migrations.AlterField(
            model_name='sector',
            name='work_end',
            field=models.TimeField(blank=True, null=True, verbose_name='work end'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='work_start',
            field=models.TimeField(blank=True, null=True, verbose_name='work start'),
        ),
    ]
