# Generated by Django 4.0.10 on 2025-09-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0015_sectorholiday_sectorholiday_idx_sector_holiday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectorholiday',
            name='date_end',
            field=models.DateField(blank=True, help_text='End date for holiday range', null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='sectorholiday',
            name='its_custom',
            field=models.BooleanField(default=False, verbose_name='Is Custom'),
        ),
        migrations.AddField(
            model_name='sectorholiday',
            name='repeat',
            field=models.BooleanField(default=False, verbose_name='Repeat Annually'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='work_end',
            field=models.TimeField(blank=True, null=True, verbose_name='work end'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='work_start',
            field=models.TimeField(blank=True, null=True, verbose_name='work start'),
        ),
    ]
