# Generated by Django 4.0.10 on 2025-09-04 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0016_sectorholiday_date_end_sectorholiday_its_custom_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sector',
            name='wordend_greater_than_workstart_check',
        ),
    ]
