# Generated by Django 4.0.10 on 2025-08-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0016_remove_sector_wordend_greater_than_workstart_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectorholiday',
            name='date_end',
            field=models.DateField(blank=True, help_text='End date for holiday range', null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='sectorholiday',
            name='is_custom',
            field=models.BooleanField(default=True, verbose_name='Is Custom'),
        ),
        migrations.AddField(
            model_name='sectorholiday',
            name='repeat',
            field=models.BooleanField(default=False, verbose_name='Repeat Annually'),
        ),
    ]
