# Generated by Django 4.0.10 on 2025-08-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0017_sectorholiday_date_end_sectorholiday_is_custom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectorholiday',
            name='is_custom',
            field=models.BooleanField(default=False, verbose_name='Is Custom'),
        ),
    ]
