# Generated by Django 4.0.4 on 2025-09-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0017_remove_sector_wordend_greater_than_workstart_check'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sectorholiday',
            name='unique_sector_holiday',
        ),
        migrations.AddConstraint(
            model_name='sectorholiday',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('sector', 'date'), name='unique_sector_holiday'),
        ),
    ]
