# Generated by Django 4.0.4 on 2025-09-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0017_remove_sector_wordend_greater_than_workstart_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='automatic_message_text',
            field=models.TextField(blank=True, null=True, verbose_name='automatic message text'),
        ),
        migrations.AddField(
            model_name='sector',
            name='is_automatic_message_active',
            field=models.BooleanField(default=False, verbose_name='is automatic message active?'),
        ),
    ]
