# Generated by Django 4.0.10 on 2025-08-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0018_alter_sectorholiday_is_custom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectorholiday',
            old_name='is_custom',
            new_name='its_custom',
        ),
    ]
