# Generated by Django 4.0.4 on 2025-10-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0019_sector_automatic_message_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='required_tags',
            field=models.BooleanField(default=False, verbose_name='required tags?'),
        ),
    ]
