# Generated by Django 4.0.4 on 2025-10-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sectors", "0021_sector_required_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectortag",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="is deleted?"),
        ),
    ]
