# Generated by Django 4.0.4 on 2025-10-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0021_sectortag_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='secondary_project',
            field=models.JSONField(blank=True, help_text='Secondary project configuration for integrated ticketers', null=True, verbose_name='Secondary Project'),
        ),
    ]
