# Generated by Django 4.0.4 on 2025-10-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sectors", "0022_sector_secondary_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="is_csat_enabled",
            field=models.BooleanField(default=False, verbose_name="is CSAT enabled?"),
        ),
    ]
