# Generated by Django 4.0.4 on 2026-04-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0023_sector_is_csat_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='custom_csat_flow_uuid',
            field=models.UUIDField(blank=True, help_text='The UUID of the custom CSAT flow', null=True, verbose_name='custom CSAT flow UUID'),
        ),
    ]
