# Generated by Django 4.0.4 on 2026-04-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0024_groupsector_created_by_groupsector_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='custom_csat_flow_uuid',
            field=models.UUIDField(blank=True, help_text='The UUID of the custom CSAT flow', null=True, verbose_name='custom CSAT flow UUID'),
        ),
    ]
