# Generated by Django 4.0.4 on 2026-05-20 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0024_groupsector_created_by_groupsector_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupsector',
            options={'verbose_name': 'Department group', 'verbose_name_plural': 'Department groups'},
        ),
        migrations.AlterModelOptions(
            name='groupsectorauthorization',
            options={'verbose_name': 'Department group authorization', 'verbose_name_plural': 'Department group authorizations'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='sectorauthorization',
            options={'verbose_name': 'Department authorization', 'verbose_name_plural': 'Department authorizations'},
        ),
        migrations.AlterModelOptions(
            name='sectorgroupsector',
            options={'verbose_name': 'Department group', 'verbose_name_plural': 'Department groups'},
        ),
        migrations.AlterModelOptions(
            name='sectorholiday',
            options={'ordering': ['date'], 'verbose_name': 'Department holiday', 'verbose_name_plural': 'Department holidays'},
        ),
        migrations.AlterModelOptions(
            name='sectortag',
            options={'ordering': ['name'], 'verbose_name': 'Department tag', 'verbose_name_plural': 'Department tags'},
        ),
        migrations.AlterField(
            model_name='groupsector',
            name='rooms_limit',
            field=models.PositiveIntegerField(verbose_name='Room limit per employee'),
        ),
        migrations.AlterField(
            model_name='groupsectorauthorization',
            name='role',
            field=models.PositiveIntegerField(choices=[(0, 'not set'), (1, 'Manager'), (2, 'Representative')], default=0, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='can_trigger_flows',
            field=models.BooleanField(default=False, help_text='Can I trigger flows (VTEX CX Platform flows integration) from this department?', verbose_name='Can trigger flows?'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='open_offline',
            field=models.BooleanField(default=True, verbose_name='Can a room be opened when all representatives are offline?'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='rooms_limit',
            field=models.PositiveIntegerField(verbose_name='Room limit per employee'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='secondary_project',
            field=models.JSONField(blank=True, help_text='Secondary project configuration for integrated ticketers', null=True, verbose_name='Secondary project'),
        ),
        migrations.AlterField(
            model_name='sectorauthorization',
            name='role',
            field=models.PositiveIntegerField(choices=[(0, 'not set'), (1, 'Manager')], default=0, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='sectorauthorization',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='sectors.sector', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='sectorholiday',
            name='date_end',
            field=models.DateField(blank=True, help_text='End date for holiday range', null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='sectorholiday',
            name='day_type',
            field=models.CharField(choices=[('closed', 'Closed'), ('custom_hours', 'Custom hours')], default='closed', max_length=20, verbose_name='Day type'),
        ),
        migrations.AlterField(
            model_name='sectorholiday',
            name='description',
            field=models.CharField(blank=True, help_text='Holiday name or special hours reason', max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sectorholiday',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Leave empty if there are no working hours', null=True, verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='sectorholiday',
            name='its_custom',
            field=models.BooleanField(default=False, verbose_name='Is custom'),
        ),
        migrations.AlterField(
            model_name='sectorholiday',
            name='repeat',
            field=models.BooleanField(default=False, verbose_name='Repeat annually'),
        ),
        migrations.AlterField(
            model_name='sectorholiday',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='sectors.sector', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='sectorholiday',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Leave empty if there are no working hours', null=True, verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='sectortag',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='sectors.sector', verbose_name='Department'),
        ),
    ]
