# Generated by Django 4.0.4 on 2026-05-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sectors", "0025_sector_custom_csat_flow_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="automatic_message_queue_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="automatic queue message text"
            ),
        ),
        migrations.AddField(
            model_name="sector",
            name="is_automatic_message_queue_active",
            field=models.BooleanField(
                default=False, verbose_name="is automatic queue message active?"
            ),
        ),
    ]
