# Generated by Django 4.0.4 on 2026-07-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sectors", "0028_alter_groupsector_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectorauthorization",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="is deleted?"),
        ),
        migrations.RemoveConstraint(
            model_name="sectorauthorization",
            name="unique_sector_auth",
        ),
        migrations.AddConstraint(
            model_name="sectorauthorization",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("sector", "permission"),
                name="unique_sector_auth",
            ),
        ),
    ]
