# Generated by Django 4.0.5 on 2022-09-26 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('sound_new_room', models.BooleanField(default=True, verbose_name='New room messages notification sound')),
                ('sound_chat_msg', models.BooleanField(default=True, verbose_name='Chat messages notification sound')),
                ('sound_action', models.BooleanField(default=True, verbose_name='Action sound')),
                ('config', models.JSONField(blank=True, null=True, verbose_name='config')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
