# Generated by Django 4.1.2 on 2023-01-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
