# Generated by Django 4.0.4 on 2026-07-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sound_chat_msg',
            field=models.BooleanField(default=True, verbose_name='Notification sound for chat messages'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sound_new_room',
            field=models.BooleanField(default=True, verbose_name='Notification sound for new room messages'),
        ),
    ]
