# Generated by Django 4.0.5 on 2022-08-16 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='ended_by',
            field=models.CharField(default=None, max_length=50, verbose_name='Ended by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='transfer_history',
            field=models.JSONField(default=None, verbose_name='Transfer History'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='contacts.contact', verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='room',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
