# Generated by Django 4.0.5 on 2022-08-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='sectors.sectortag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='room',
            name='transfer_history',
            field=models.JSONField(blank=True, null=True, verbose_name='Transfer History'),
        ),
    ]
