# Generated by Django 4.0.5 on 2022-08-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='custom_fields',
            field=models.JSONField(blank=True, null=True, verbose_name='custom fields'),
        ),
    ]
