# Generated by Django 4.0.5 on 2022-06-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_contact_alter_room_tags_alter_room_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='started_at',
        ),
    ]
