# Generated by Django 4.0.5 on 2022-08-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='callback_url',
            field=models.URLField(default=None, verbose_name='Callback URL'),
            preserve_default=False,
        ),
    ]
