# Generated by Django 4.0.5 on 2022-08-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0002_alter_sector_options_alter_sector_project'),
        ('rooms', '0002_room_ended_by_room_transfer_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='ended_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ended by'),
        ),
        migrations.AlterField(
            model_name='room',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='rooms', to='sectors.sectortag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='room',
            name='transfer_history',
            field=models.JSONField(blank=True, verbose_name='Transfer History'),
        ),
    ]
