# Generated by Django 4.0.4 on 2022-06-10 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
        ("rooms", "0002_room_is_active_alter_room_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contacts.contact",
                verbose_name="messages",
            ),
        ),
    ]
