# Generated by Django 4.0.5 on 2022-06-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_remove_room_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='agent_history',
            field=models.TextField(blank=True, null=True, verbose_name='Agent History'),
        ),
    ]
