# Generated by Django 4.0.5 on 2022-08-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_ended_by_alter_room_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='transfer_history',
            field=models.JSONField(blank=True, null=True, verbose_name='Transfer History'),
        ),
    ]
