# Generated by Django 4.0.5 on 2022-08-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_callback_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='callback_url',
            field=models.URLField(blank=True, null=True, verbose_name='Callback URL'),
        ),
    ]
