# Generated by Django 4.0.5 on 2022-07-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0002_sectorauthorization_sectortag_sector_is_deleted_and_more'),
        ('rooms', '0004_room_agent_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomTag',
        ),
        migrations.RemoveField(
            model_name='room',
            name='agent_history',
        ),
        migrations.AlterField(
            model_name='room',
            name='tags',
            field=models.ManyToManyField(related_name='rooms', to='sectors.sectortag', verbose_name='tags'),
        ),
    ]
