# Generated by Django 4.1.2 on 2022-12-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0006_room_unique_contact_queue_is_activetrue_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="is_waiting",
            field=models.BooleanField(
                default=False, verbose_name="is waiting for answer?"
            ),
        ),
    ]
