# Generated by Django 4.1.2 on 2022-12-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0007_room_is_waiting"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="urn",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True, verbose_name="urn"
            ),
        ),
    ]
