# Generated by Django 4.1.2 on 2022-12-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0008_room_urn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="urn",
            field=models.CharField(
                blank=True, default="", max_length=200, null=True, verbose_name="urn"
            ),
        ),
    ]
