# Generated by Django 4.1.2 on 2023-01-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0008_room_urn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="callback_url",
            field=models.TextField(blank=True, null=True, verbose_name="Callback URL"),
        ),
    ]
