# Generated by Django 4.1.2 on 2024-03-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0011_room_protocol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="protocol",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="protocol"
            ),
        ),
    ]
