# Generated by Django 4.1.2 on 2024-07-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0011_room_protocol"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="service_chat",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="service chat"
            ),
        ),
    ]
