# Generated by Django 4.1.2 on 2024-09-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0012_room_service_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="project_uuid",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="project_uuid"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["project_uuid"], name="rooms_room_project_890f5f_idx"
            ),
        ),
    ]
