# Generated by Django 4.1.2 on 2024-12-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0013_room_project_uuid_room_rooms_room_project_890f5f_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="ticket_uuid",
            field=models.UUIDField(blank=True, null=True, verbose_name="ticket uuid"),
        ),
    ]
