# Generated by Django 4.1.2 on 2025-01-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0014_room_ticket_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="user_assigned_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="User assigned at"
            ),
        ),
    ]
