# Generated by Django 4.1.2 on 2025-02-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0015_room_user_assigned_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="config",
            field=models.JSONField(blank=True, null=True, verbose_name="config"),
        ),
    ]
