# Generated by Django 4.1.2 on 2025-06-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0017_roompin_roompin_unique_room_user_room_pin"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="added_to_queue_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Added to queue at"
            ),
        ),
    ]
