# Generated by Django 4.1.2 on 2025-06-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0017_roompin_roompin_unique_room_user_room_pin"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="full_transfer_history",
            field=models.JSONField(
                blank=True,
                default=list,
                null=True,
                verbose_name="Full Transfer History",
            ),
        ),
    ]
