# Generated by Django 4.1.2 on 2025-07-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0018_room_full_transfer_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="added_to_queue_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Added to queue at"
            ),
        ),
    ]
