# Generated by Django 4.1.2 on 2025-07-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0020_roomnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomnote",
            name="is_deletable",
            field=models.BooleanField(default=True, verbose_name="is deletable"),
        ),
    ]
