# Generated by Django 4.0.4 on 2025-09-24 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0015_automaticmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0020_room_first_user_assigned_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomNote',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('text', models.TextField(verbose_name='text')),
                ('is_deletable', models.BooleanField(default=True, verbose_name='is deletable')),
                ('message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_note', to='msgs.message', verbose_name='message')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='rooms.room', verbose_name='room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_notes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Room Note',
                'verbose_name_plural': 'Room Notes',
                'ordering': ['-created_on'],
            },
        ),
    ]
