# Generated by Django 4.0.4 on 2025-09-15 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0015_automaticmessage'),
        ('rooms', '0021_roomnote_is_deletable'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomnote',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_note', to='msgs.message', verbose_name='message'),
        ),
    ]
