# Generated by Django 4.0.4 on 2026-01-14 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0010_add_index_to_contact_name'),
        ('msgs', '0017_alter_messagemedia_media_file'),
        ('rooms', '0022_roomnote_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_rooms_by_user', to=settings.AUTH_USER_MODEL, verbose_name='closed by'),
        ),
        migrations.AddField(
            model_name='room',
            name='first_user_assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First user assigned at'),
        ),
        migrations.AddField(
            model_name='room',
            name='last_interaction',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last interaction'),
        ),
        migrations.AddField(
            model_name='room',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='msgs.message', verbose_name='Last message'),
        ),
        migrations.AddField(
            model_name='room',
            name='last_message_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contacts.contact', verbose_name='Last message contact'),
        ),
        migrations.AddField(
            model_name='room',
            name='last_message_text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Last message text'),
        ),
        migrations.AddField(
            model_name='room',
            name='last_message_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last message user'),
        ),
        migrations.AddField(
            model_name='room',
            name='last_unread_message_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last unread message at'),
        ),
        migrations.AddField(
            model_name='room',
            name='unread_messages_count',
            field=models.IntegerField(default=0, verbose_name='Unread messages count'),
        ),
    ]
