# Generated by Django 4.0.4 on 2025-09-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0022_roomnote_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="first_user_assigned_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="First user assigned at"
            ),
        ),
    ]
