# Generated by Django 4.0.4 on 2025-12-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0023_room_first_user_assigned_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="last_unread_message_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last unread message at"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="unread_messages_count",
            field=models.IntegerField(default=0, verbose_name="Unread messages count"),
        ),
    ]
