# Generated by Django 4.0.4 on 2026-01-05 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_add_index_to_contact_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msgs', '0017_alter_messagemedia_media_file'),
        ('rooms', '0023_room_last_contact_interaction_room_last_interaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='last_contact_interaction',
        ),
        migrations.RemoveField(
            model_name='room',
            name='last_message_uuid',
        ),
        migrations.AddField(
            model_name='room',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='msgs.message', verbose_name='Last message'),
        ),
        migrations.AddField(
            model_name='room',
            name='last_message_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contacts.contact', verbose_name='Last message contact'),
        ),
        migrations.AddField(
            model_name='room',
            name='last_message_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last message user'),
        ),
    ]
