# Generated by Django 4.0.4 on 2026-01-06 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0024_remove_room_last_contact_interaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_rooms', to=settings.AUTH_USER_MODEL, verbose_name='closed by'),
        ),
    ]
