# Generated by Django 4.0.4 on 2026-01-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0024_room_last_unread_message_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_contact_interaction',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last contact interaction'),
        ),
        migrations.AddField(
            model_name='room',
            name='last_interaction',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last interaction'),
        ),
        migrations.AddField(
            model_name='room',
            name='last_message_text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Last message text'),
        ),
        migrations.AddField(
            model_name='room',
            name='last_message_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='Last message UUID'),
        ),
    ]
