# Generated by Django 4.0.4 on 2026-01-12 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0025_room_closed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_rooms_by_user', to=settings.AUTH_USER_MODEL, verbose_name='closed by'),
        ),
    ]
