# Generated by Django 4.0.4 on 2026-01-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0026_alter_room_closed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='automatic_message_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Automatic message sent at'),
        ),
        migrations.AddField(
            model_name='room',
            name='first_agent_message_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First agent message at'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_agent_messages',
            field=models.BooleanField(default=False, verbose_name='Has agent messages'),
        ),
    ]
