# Generated by Django 4.0.4 on 2026-01-08 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0017_alter_messagemedia_media_file"),
        ("rooms", "0027_room_last_message_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomnote",
            name="message",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="internal_note",
                to="msgs.message",
                verbose_name="message",
            ),
        ),
    ]
