# Generated by Django 4.0.4 on 2026-06-23 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0035_project_is_chats_summary_enabled"),
        ("rooms", "0036_populate_roompin_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roompin",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_pins",
                to="projects.project",
                verbose_name="project",
            ),
        ),
    ]
