# Generated by Django 4.0.4 on 2026-07-02 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0028_alter_groupsector_options_and_more'),
        ('msgs', '0022_alter_messagemedia_options_and_more'),
        ('rooms', '0037_alter_roompin_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomnote',
            options={'ordering': ['-created_on'], 'verbose_name': 'Room note', 'verbose_name_plural': 'Room notes'},
        ),
        migrations.AlterModelOptions(
            name='roompin',
            options={'verbose_name': 'Room pin', 'verbose_name_plural': 'Room pins'},
        ),
        migrations.AlterField(
            model_name='room',
            name='full_transfer_history',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Full transfer history'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_waiting',
            field=models.BooleanField(default=False, verbose_name='is waiting for an answer?'),
        ),
        migrations.AlterField(
            model_name='room',
            name='protocol',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Protocol'),
        ),
        migrations.AlterField(
            model_name='room',
            name='service_chat',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Service chat'),
        ),
        migrations.AlterField(
            model_name='room',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='sectors.sectortag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='room',
            name='transfer_history',
            field=models.JSONField(blank=True, null=True, verbose_name='Transfer history'),
        ),
        migrations.AlterField(
            model_name='roomnote',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_note', to='msgs.message', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='roompin',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created on'),
        ),
    ]
