# Generated by Django 4.0.4 on 2026-08-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0039_rooms_violation_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_message_metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='Last message metadata'),
        ),
    ]
