# Generated by Django 4.0.4 on 2025-12-29 14:20

import chats.apps.archive_chats.uploads
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0022_room_last_unread_message_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveConversationsJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, help_text='The date and time when the job started', null=True, verbose_name='Started at')),
            ],
            options={
                'verbose_name': 'Archive Conversations Job',
                'verbose_name_plural': 'Archive Conversations Jobs',
            },
        ),
        migrations.CreateModel(
            name='RoomArchivedConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING_MESSAGES', 'Processing Messages'), ('UPLOADING_MEDIA', 'Uploading Media'), ('UPLOADING_MESSAGES_FILE', 'Uploading Messages File'), ('DELETING_MESSAGES_FROM_DB', 'Deleting Messages From Db'), ('FINISHED', 'Finished'), ('FAILED', 'Failed')], default='PENDING', max_length=25, verbose_name='Status')),
                ('file', models.FileField(help_text='The file that contains the archived conversation', max_length=255, upload_to=chats.apps.archive_chats.uploads.upload_to, verbose_name='File')),
                ('archive_process_started_at', models.DateTimeField(blank=True, help_text='The date and time when the archive process started', null=True, verbose_name='Archive process started at')),
                ('messages_deleted_at', models.DateTimeField(blank=True, help_text='The date and time when the messages were deleted from the database', null=True, verbose_name='Messages deleted at')),
                ('archive_process_finished_at', models.DateTimeField(blank=True, help_text='The date and time when the archive process was finished', null=True, verbose_name='Archive process finished at')),
                ('failed_at', models.DateTimeField(blank=True, help_text='The date and time when the archive process failed', null=True, verbose_name='Failed at')),
                ('errors', models.JSONField(blank=True, help_text='The errors that occurred during the archive process', null=True, verbose_name='Errors')),
                ('job', models.ForeignKey(help_text='The job that archived the conversation', on_delete=django.db.models.deletion.CASCADE, related_name='room_archived_conversations', to='archive_chats.archiveconversationsjob', verbose_name='Job')),
                ('room', models.OneToOneField(help_text='The room that was archived', on_delete=django.db.models.deletion.CASCADE, related_name='archived_conversations', to='rooms.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Room Archived Conversation',
                'verbose_name_plural': 'Room Archived Conversations',
            },
        ),
    ]
