# Generated by Django 4.0.4 on 2026-03-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_chats', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='roomarchivedconversation',
            constraint=models.UniqueConstraint(fields=('room',), name='unique_room_archived_conversation'),
        ),
    ]
