# Generated by Django 4.0.4 on 2026-07-02 14:31

import chats.apps.archive_chats.uploads
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0039_alter_roomnote_options_alter_roompin_options_and_more'),
        ('archive_chats', '0002_roomarchivedconversation_unique_room_archived_conversation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archiveconversationsjob',
            options={'verbose_name': 'Archive conversation job', 'verbose_name_plural': 'Archive conversation jobs'},
        ),
        migrations.AlterModelOptions(
            name='roomarchivedconversation',
            options={'verbose_name': 'Archived room conversation', 'verbose_name_plural': 'Archived room conversations'},
        ),
        migrations.AlterField(
            model_name='archiveconversationsjob',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='The date and time the job started', null=True, verbose_name='Started at'),
        ),
        migrations.AlterField(
            model_name='roomarchivedconversation',
            name='archive_process_finished_at',
            field=models.DateTimeField(blank=True, help_text='Date and time the archive process was completed', null=True, verbose_name='Archiving finished at'),
        ),
        migrations.AlterField(
            model_name='roomarchivedconversation',
            name='archive_process_started_at',
            field=models.DateTimeField(blank=True, help_text='Date and time the archive process started', null=True, verbose_name='Archiving started at'),
        ),
        migrations.AlterField(
            model_name='roomarchivedconversation',
            name='errors',
            field=models.JSONField(blank=True, help_text='Errors that occurred during archiving', null=True, verbose_name='Errors'),
        ),
        migrations.AlterField(
            model_name='roomarchivedconversation',
            name='failed_at',
            field=models.DateTimeField(blank=True, help_text='Date and time the archive process failed', null=True, verbose_name='Failed at'),
        ),
        migrations.AlterField(
            model_name='roomarchivedconversation',
            name='file',
            field=models.FileField(help_text='File containing the archived conversation', max_length=255, upload_to=chats.apps.archive_chats.uploads.upload_to, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='roomarchivedconversation',
            name='job',
            field=models.ForeignKey(help_text='Job that archived the conversation', on_delete=django.db.models.deletion.CASCADE, related_name='room_archived_conversations', to='archive_chats.archiveconversationsjob', verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='roomarchivedconversation',
            name='messages_deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time the messages were deleted from the database', null=True, verbose_name='Messages deleted at'),
        ),
        migrations.AlterField(
            model_name='roomarchivedconversation',
            name='room',
            field=models.ForeignKey(help_text='Archived room', on_delete=django.db.models.deletion.CASCADE, related_name='archived_conversations', to='rooms.room', verbose_name='Room'),
        ),
    ]
