# Generated by Django 4.0.4

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0036_alter_agentstatuslog_options_and_more"),
        ("sectors", "0029_sectorauthorization_is_deleted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CopilotIntegration",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="Modified on"),
                ),
                (
                    "copilot_project_uuid",
                    models.UUIDField(verbose_name="Copilot project UUID"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "assigned_agents",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Assigned agents"
                    ),
                ),
                (
                    "connection",
                    models.JSONField(default=dict, verbose_name="Connection"),
                ),
                (
                    "connected_on",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Connected on"
                    ),
                ),
                (
                    "copilot_created_on",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Copilot created on"
                    ),
                ),
                (
                    "connected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="copilot_integrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Connected by",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copilot_integrations",
                        to="projects.project",
                        verbose_name="Live Desk project",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copilot_integrations",
                        to="sectors.sector",
                        verbose_name="Sector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Copilot integration",
                "verbose_name_plural": "Copilot integrations",
            },
        ),
        migrations.AddConstraint(
            model_name="copilotintegration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sector__isnull", True)),
                fields=("project",),
                name="unique_copilot_per_project_without_sector",
            ),
        ),
        migrations.AddConstraint(
            model_name="copilotintegration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sector__isnull", False)),
                fields=("sector",),
                name="unique_copilot_per_sector",
            ),
        ),
    ]
