# Generated by Django 4.0.4 on 2026-09-25 12:20

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0041_room_channel_uuid'),
        ('assisted_sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotMessageFeedback',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('message_id', models.CharField(max_length=255, verbose_name='Message ID')),
                ('liked', models.BooleanField(verbose_name='Liked?')),
                ('text', models.CharField(blank=True, default='', max_length=150, verbose_name='Text')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='Tags')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_message_feedbacks', to='rooms.room', verbose_name='Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_message_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Copilot message feedback',
                'verbose_name_plural': 'Copilot message feedbacks',
            },
        ),
        migrations.AddConstraint(
            model_name='copilotmessagefeedback',
            constraint=models.UniqueConstraint(fields=('room', 'message_id', 'user'), name='unique_copilot_message_feedback_per_user'),
        ),
    ]
