# Generated by Django 4.0.4 on 2022-06-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="seen",
            field=models.BooleanField(default=False, verbose_name="Was it seen?"),
        ),
    ]
