# Generated by Django 4.0.5 on 2022-09-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0002_alter_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemedia',
            name='media',
        ),
        migrations.AddField(
            model_name='messagemedia',
            name='content_type',
            field=models.CharField(default='json', max_length=50, verbose_name='Content Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagemedia',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Media File'),
        ),
        migrations.AddField(
            model_name='messagemedia',
            name='media_url',
            field=models.URLField(blank=True, null=True, verbose_name='Media url'),
        ),
    ]
