# Generated by Django 4.1.2 on 2023-01-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0004_alter_message_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagemedia",
            name="media_url",
            field=models.TextField(blank=True, null=True, verbose_name="Media url"),
        ),
    ]
