# Generated by Django 4.1.2 on 2023-05-02 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0006_alter_messagemedia_content_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["created_on"],
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
    ]
