# Generated by Django 4.1.2 on 2024-12-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0007_alter_message_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="external_id",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="External ID"
            ),
        ),
    ]
