# Generated by Django 4.1.2 on 2025-01-06 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0007_alter_message_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="created_on",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Created on",
            ),
        ),
        migrations.AlterField(
            model_name="messagemedia",
            name="created_on",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Created on",
            ),
        ),
    ]
