# Generated by Django 4.1.2 on 2023-10-25 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0001_initial"),
        ("msgs", "0007_alter_message_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagemedia",
            name="discussion_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medias",
                to="discussions.discussionmessage",
                verbose_name="discussion message",
            ),
        ),
        migrations.AlterField(
            model_name="messagemedia",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medias",
                to="msgs.message",
                verbose_name="message",
            ),
        ),
    ]
