# Generated by Django 4.1.2 on 2024-10-17 18:34

import chats.core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0007_alter_message_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagemedia",
            name="media_file",
            field=models.FileField(
                blank=True,
                max_length=300,
                null=True,
                storage=chats.core.storage_backends.PrivateMediaStorage(),
                upload_to="",
                verbose_name="Media File",
            ),
        ),
    ]
