# Generated by Django 4.1.2 on 2024-12-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0008_message_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="status",
            field=models.JSONField(
                blank=True, null=True, verbose_name="message status"
            ),
        ),
    ]
