# Generated by Django 4.1.2 on 2025-04-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0008_alter_message_created_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="external_id",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="External ID"
            ),
        ),
    ]
