# Generated by Django 4.1.2 on 2025-03-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0008_alter_message_created_on_and_more"),
        ("msgs", "0009_message_status"),
    ]

    operations = []
