# Generated by Django 4.1.2 on 2025-05-16 19:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0011_alter_message_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessageReplyIndex",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="Modified on"),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Created on",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="External ID",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reply_indexes",
                        to="msgs.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message Reply Index",
                "verbose_name_plural": "Chat Message Reply Indexes",
            },
        ),
    ]
