# Generated by Django 4.1.2 on 2025-06-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0012_chatmessagereplyindex"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="status",
            field=models.JSONField(
                blank=True, null=True, verbose_name="message status"
            ),
        ),
    ]
