# Generated by Django 4.1.2 on 2025-07-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0013_message_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_delivered",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="message is delivered",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="message is read"
            ),
        ),
    ]
