# Generated by Django 4.0.4 on 2025-09-09 14:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0019_room_added_to_queue_at'),
        ('msgs', '0014_message_is_delivered_message_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomaticMessage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='automatic_message', to='msgs.message')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='automatic_message', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Automatic Message',
                'verbose_name_plural': 'Automatic Messages',
            },
        ),
    ]
