# Generated by Django 4.0.4 on 2025-12-09 19:05

import chats.apps.msgs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0016_messagemedia_message_media_content_type_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemedia',
            name='media_file',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to=chats.apps.msgs.models.message_media_upload_to, verbose_name='Media File'),
        ),
    ]
