# Generated by Django 4.0.4 on 2026-05-20 20:25

import chats.apps.msgs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0017_alter_messagemedia_media_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagemedia',
            options={'verbose_name': 'Message media', 'verbose_name_plural': 'Message media'},
        ),
        migrations.AlterField(
            model_name='message',
            name='is_delivered',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='message was delivered'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='message was read'),
        ),
        migrations.AlterField(
            model_name='messagemedia',
            name='content_type',
            field=models.CharField(max_length=300, verbose_name='Content type'),
        ),
        migrations.AlterField(
            model_name='messagemedia',
            name='media_file',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to=chats.apps.msgs.models.message_media_upload_to, verbose_name='Media file'),
        ),
        migrations.AlterField(
            model_name='messagemedia',
            name='media_url',
            field=models.TextField(blank=True, null=True, verbose_name='Media URL'),
        ),
        migrations.AlterField(
            model_name='messagemedia',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='msgs.message', verbose_name='Message'),
        ),
    ]
