# Generated by Django 4.0.4 on 2026-07-20 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_alter_agentstatuslog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msgs', '0022_alter_messagemedia_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkMessageSend',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('text', models.TextField(verbose_name='text')),
                ('filter_snapshot', models.JSONField(blank=True, default=dict, verbose_name='filter snapshot')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('FINISHED', 'Finished')], default='PENDING', max_length=20, verbose_name='status')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_message_sends', to='projects.project', verbose_name='project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_message_sends', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Bulk message send',
                'verbose_name_plural': 'Bulk message sends',
            },
        ),
    ]
