# Generated by Django 4.0.4 on 2026-07-20 18:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0023_bulkmessagesend'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkMessageSendMessage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('bulk_message_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_messages', to='msgs.bulkmessagesend', verbose_name='bulk message send')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_message_send_message', to='msgs.message', verbose_name='message')),
            ],
            options={
                'verbose_name': 'Bulk message send message',
                'verbose_name_plural': 'Bulk message send messages',
            },
        ),
    ]
