# Generated by Django 4.0.4 on 2026-07-23 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0039_alter_roomnote_options_alter_roompin_options_and_more"),
        ("msgs", "0024_bulkmessagesendmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkmessagesendmessage",
            name="errors",
            field=models.JSONField(blank=True, null=True, verbose_name="errors"),
        ),
        migrations.AddField(
            model_name="bulkmessagesendmessage",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bulk_message_send_messages",
                to="rooms.room",
                verbose_name="room",
            ),
        ),
        migrations.AddField(
            model_name="bulkmessagesendmessage",
            name="status",
            field=models.CharField(
                choices=[("SUCCESS", "Success"), ("FAILED", "Failed")],
                default="SUCCESS",
                max_length=20,
                verbose_name="status",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bulkmessagesendmessage",
            name="message",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bulk_message_send_message",
                to="msgs.message",
                verbose_name="message",
            ),
        ),
    ]
