# Generated by Django 4.0.4 on 2026-07-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0026_bulkmessagesendmessage_populate_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkmessagesend',
            name='rooms_qty',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='rooms quantity'),
        ),
    ]
