# Generated by Django 4.0.4 on 2026-08-12 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0036_alter_agentstatuslog_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("msgs", "0027_bulkmessagesend_rooms_qty"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkQuickMessageSend",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="Modified on"),
                ),
                ("text", models.TextField(verbose_name="text")),
                (
                    "contacts",
                    models.JSONField(blank=True, null=True, verbose_name="contacts"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("FINISHED", "Finished"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "rooms_qty",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="rooms quantity"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_quick_message_sends",
                        to="projects.project",
                        verbose_name="project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_quick_message_sends",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulk quick message send",
                "verbose_name_plural": "Bulk quick message sends",
            },
        ),
    ]
