# Generated by Django 4.0.4 on 2026-08-13 13:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0039_rooms_violation_indexes"),
        ("msgs", "0028_bulkquickmessagesend"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkQuickMessageSendMessage",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="Modified on"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILED", "Failed")],
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "errors",
                    models.JSONField(blank=True, null=True, verbose_name="errors"),
                ),
                (
                    "bulk_quick_message_send",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_quick_messages",
                        to="msgs.bulkquickmessagesend",
                        verbose_name="bulk quick message send",
                    ),
                ),
                (
                    "message",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_quick_message_send_message",
                        to="msgs.message",
                        verbose_name="message",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_quick_message_send_messages",
                        to="rooms.room",
                        verbose_name="room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulk quick message send message",
                "verbose_name_plural": "Bulk quick message send messages",
            },
        ),
    ]
