# Generated by Django 4.0.4 on 2026-08-31 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0039_rooms_violation_indexes'),
        ('msgs', '0028_bulkquickmessagesend_bulkquickmessagesendmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemedia',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='rooms.room', verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='messagemedia',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='msgs.message', verbose_name='Message'),
        ),
    ]
