# Generated by Django 4.0.4 on 2026-05-20 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csat', '0002_csatflowprojectconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csatflowprojectconfig',
            options={'verbose_name': 'CSAT flow project config', 'verbose_name_plural': 'CSAT flow project configs'},
        ),
        migrations.AlterModelOptions(
            name='csatsurvey',
            options={'verbose_name': 'CSAT survey', 'verbose_name_plural': 'CSAT surveys'},
        ),
    ]
