# Generated by Django 4.1.2 on 2022-12-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roommetrics",
            name="interaction_time",
            field=models.IntegerField(default=0, verbose_name="Room interaction time"),
        ),
    ]
