# Generated by Django 4.1.2 on 2023-01-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roommetrics",
            options={
                "verbose_name": "Room Metric",
                "verbose_name_plural": "Rooms Metrics",
            },
        ),
        migrations.AddField(
            model_name="roommetrics",
            name="interaction_time",
            field=models.IntegerField(default=0, verbose_name="Room interaction time"),
        ),
    ]
