# Generated by Django 4.1.2 on 2022-11-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roommetrics",
            name="message_response_time",
            field=models.IntegerField(default=0, verbose_name="Messages response time"),
        ),
        migrations.AlterField(
            model_name="roommetrics",
            name="queued_count",
            field=models.IntegerField(default=0, verbose_name="Queued count"),
        ),
    ]
