# Generated by Django 4.1.2 on 2023-02-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_roommetrics_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roommetrics",
            name="transfer_count",
            field=models.IntegerField(default=0, verbose_name="Room transfer count"),
        ),
    ]
