# Generated by Django 4.1.2 on 2022-12-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_roommetrics_message_response_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roommetrics",
            name="waiting_time",
            field=models.IntegerField(default=0, verbose_name="Room Waiting time"),
        ),
    ]
