# Generated by Django 4.2.23 on 2025-08-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_reportstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("ready", "Ready"),
                    ("in_progress", "In Progress"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
