# Generated by Django 4.0.4 on 2025-10-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_reportstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommetrics',
            name='first_response_time',
            field=models.IntegerField(default=0, verbose_name='First response time'),
        ),
    ]
