# Generated by Django 4.0.4 on 2025-10-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_roommetrics_first_response_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommetrics',
            name='first_response_time',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='First response time'),
        ),
    ]
