# Generated by Django 4.0.4 on 2025-11-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_roommetrics_first_response_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommetrics',
            name='conversation_duration',
            field=models.IntegerField(blank=True, default=None, help_text='The duration of the conversation between user and contact in seconds', null=True, verbose_name='Conversation duration'),
        ),
    ]
