# Generated by Django 4.0.4 on 2026-05-20 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0030_alter_roomnote_options_alter_roompin_options_and_more'),
        ('dashboard', '0008_reportstatus_retry_count_and_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roommetrics',
            options={'verbose_name': 'Room metric', 'verbose_name_plural': 'Room metrics'},
        ),
        migrations.AlterField(
            model_name='roommetrics',
            name='message_response_time',
            field=models.IntegerField(default=0, verbose_name='Message response time'),
        ),
        migrations.AlterField(
            model_name='roommetrics',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metric', to='rooms.room', verbose_name='Room metric'),
        ),
        migrations.AlterField(
            model_name='roommetrics',
            name='waiting_time',
            field=models.IntegerField(default=0, verbose_name='Room waiting time'),
        ),
    ]
