from .dead_letter_consumer import DeadLetterConsumer
from .permission_consumer import ProjectPermissionConsumer
from .project_consumer import OldProjectConsumer, WeniEDAProjectConsumer
from .project_update_consumer import ProjectUpdateConsumer
from .sector_consumer import SectorConsumer
from .template_type_consumer import TemplateTypeConsumer
