from .template_type_consumer import TemplateTypeConsumer
from .project_consumer import ProjectConsumer
from .dead_letter_consumer import DeadLetterConsumer
from .permission_consumer import ProjectPermissionConsumer
from .sector_consumer import SectorConsumer
