# Generated by Django 4.0.4 on 2022-06-10 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shortcut", models.CharField(max_length=50, verbose_name="shortcut")),
                ("text", models.TextField(verbose_name="text")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="quick_messages",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quick Message",
                "verbose_name_plural": "Quick Messages",
            },
        ),
    ]
