# Generated by Django 4.0.5 on 2022-09-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickmessages', '0002_alter_quickmessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickmessage',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='title'),
        ),
    ]
