# Generated by Django 4.1.2 on 2023-07-18 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sectors", "0005_remove_sector_rooms_limit_greater_than_zero"),
        ("quickmessages", "0003_quickmessage_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="quickmessage",
            name="sector",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quick_message",
                to="sectors.sector",
                verbose_name="sector",
            ),
        ),
    ]
