# Generated by Django 4.0.4 on 2026-07-02 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0028_alter_groupsector_options_and_more'),
        ('quickmessages', '0005_quickmessage_created_by_quickmessage_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quickmessage',
            options={'verbose_name': 'Quick message', 'verbose_name_plural': 'Quick messages'},
        ),
        migrations.AlterField(
            model_name='quickmessage',
            name='sector',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quick_message', to='sectors.sector', verbose_name='Department'),
        ),
    ]
