# Generated by Django 4.1.2 on 2025-05-14 18:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rooms", "0016_room_config"),
        ("ai_features", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorySummary",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="Modified on"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("DONE", "Done"),
                            ("UNAVAILABLE ", "Unavailable"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "feature_prompt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai_features.featureprompt",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rooms.room"
                    ),
                ),
            ],
            options={
                "verbose_name": "History Summary",
                "verbose_name_plural": "History Summaries",
            },
        ),
    ]
