# Generated by Django 4.1.2 on 2025-05-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history_summary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historysummary",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("DONE", "Done"),
                    ("UNAVAILABLE", "Unavailable"),
                ],
                default="PENDING",
                max_length=12,
            ),
        ),
    ]
