# Generated by Django 4.1.2 on 2025-06-25 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("history_summary", "0003_change_unavailable_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorySummaryFeedback",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="Modified on"),
                ),
                ("liked", models.BooleanField(verbose_name="Liked?")),
                (
                    "feedback",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Feedback"
                    ),
                ),
                (
                    "history_summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="history_summary.historysummary",
                        verbose_name="History Summary",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_summary_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "History Summary Feedback",
                "verbose_name_plural": "History Summary Feedbacks",
            },
        ),
        migrations.AddConstraint(
            model_name="historysummaryfeedback",
            constraint=models.UniqueConstraint(
                fields=("history_summary", "user"),
                name="unique_history_summary_user_feedback",
            ),
        ),
    ]
