# Generated by Django 4.0.4 on 2025-12-12 14:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_summary', '0004_historysummaryfeedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historysummaryfeedback',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
