# Generated by Django 4.0.4 on 2026-07-02 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history_summary', '0005_historysummaryfeedback_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historysummary',
            options={'verbose_name': 'History summary', 'verbose_name_plural': 'History summaries'},
        ),
        migrations.AlterModelOptions(
            name='historysummaryfeedback',
            options={'verbose_name': 'History summary feedback', 'verbose_name_plural': 'History summary feedback'},
        ),
        migrations.AlterField(
            model_name='historysummaryfeedback',
            name='history_summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='history_summary.historysummary', verbose_name='History summary'),
        ),
    ]
