# Generated by Django 4.0.4 on 2026-04-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('improve_user_message', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='messageimprovementstatus',
            index=models.Index(fields=['project', 'type'], name='idx_improv_project_type'),
        ),
    ]
