# Generated by Django 4.0.5 on 2022-08-24 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('project_flow', models.CharField(max_length=50, verbose_name='Flow project uuid')),
                ('ticketer_uuid', models.CharField(max_length=50, verbose_name='Flow ticketer uuid')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
