# Generated by Django 4.0.5 on 2022-07-26 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpermission',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='projects.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='projectpermission',
            name='role',
            field=models.PositiveIntegerField(choices=[(0, 'not set'), (1, 'admin'), (2, 'external')], default=0, verbose_name='role'),
        ),
    ]
