# Generated by Django 4.0.5 on 2022-09-01 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_flow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flow',
            options={'verbose_name': 'Flow integration', 'verbose_name_plural': 'Flow integration'},
        ),
        migrations.RenameField(
            model_name='flow',
            old_name='project_flow',
            new_name='project_flows_uuid',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='ticketer_uuid',
        ),
        migrations.AddField(
            model_name='flow',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='projects.project', verbose_name='Project'),
            preserve_default=False,
        ),
    ]
