# Generated by Django 4.0.5 on 2022-09-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_flow_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpermission',
            name='role',
            field=models.PositiveIntegerField(choices=[(0, 'not set'), (1, 'admin'), (2, 'agent'), (3, 'service manager')], default=0, verbose_name='role'),
        ),
    ]
