# Generated by Django 4.0.5 on 2022-09-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectpermission_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpermission',
            name='status',
            field=models.CharField(choices=[(0, 'not set'), (1, 'admin'), (2, 'agent'), (3, 'service manager')], default='OFFLINE', max_length=10, verbose_name='User Status'),
        ),
    ]
