# Generated by Django 4.0.5 on 2022-09-13 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectpermission_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flow',
        ),
    ]
