# Generated by Django 4.0.5 on 2022-09-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_delete_flow'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projectpermission',
            constraint=models.UniqueConstraint(fields=('user', 'project'), name='unique_user_permission'),
        ),
    ]
