# Generated by Django 4.1.2 on 2022-12-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_projectpermission_first_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="flows_authorization",
            field=models.CharField(
                blank=True,
                max_length=36,
                null=True,
                verbose_name="Flows Authorization Token",
            ),
        ),
    ]
