# Generated by Django 4.1.2 on 2022-11-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_projectpermission_first_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectpermission",
            name="status",
            field=models.CharField(
                choices=[
                    ("ONLINE", "online"),
                    ("OFFLINE", "offline"),
                    ("AWAY", "away"),
                    ("BUSY", "busy"),
                ],
                default="OFFLINE",
                max_length=10,
                verbose_name="User Status",
            ),
        ),
    ]
