# Generated by Django 4.1.2 on 2022-12-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_alter_projectpermission_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectpermission",
            name="first_access",
            field=models.BooleanField(
                default=True, verbose_name="Is it the first access of user?"
            ),
        ),
        migrations.AlterField(
            model_name="projectpermission",
            name="role",
            field=models.PositiveIntegerField(
                choices=[(0, "not set"), (1, "admin"), (2, "Attendant")],
                default=0,
                verbose_name="role",
            ),
        ),
    ]
