# Generated by Django 4.1.2 on 2022-12-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_project_flows_authorization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="flows_authorization",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Flows Authorization Token",
            ),
        ),
    ]
