# Generated by Django 4.1.2 on 2023-01-26 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contacts", "0004_alter_contact_email"),
        ("projects", "0012_alter_project_flows_authorization"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkContact",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="Modified on"),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_users",
                        to="contacts.contact",
                        verbose_name="Contact",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_contacts",
                        to="projects.project",
                        verbose_name="project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_contacts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Linked Contact",
                "verbose_name_plural": "Linked Contacts",
            },
        ),
        migrations.AddConstraint(
            model_name="linkcontact",
            constraint=models.UniqueConstraint(
                fields=("contact", "project"), name="unique_link_contact_per_project"
            ),
        ),
    ]
