# Generated by Django 4.1.2 on 2023-01-31 17:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_linkcontact_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowStart",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="Modified on"),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="External ID",
                    ),
                ),
                (
                    "flow",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="flow ID"
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flowstarts",
                        to="projects.projectpermission",
                        verbose_name="Permission",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flowstarts",
                        to="projects.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flow Start",
                "verbose_name_plural": "Flow Starts",
            },
        ),
        migrations.CreateModel(
            name="ContactGroupFlowReference",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="Modified on"),
                ),
                (
                    "receiver_type",
                    models.CharField(max_length=50, verbose_name="Receiver Type"),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="External ID",
                    ),
                ),
                (
                    "flow_start",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="projects.flowstart",
                        verbose_name="Flow Start",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flow contact/group Reference",
                "verbose_name_plural": "Flow contact/group References",
            },
        ),
    ]
