# Generated by Django 4.1.2 on 2023-04-13 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0009_alter_room_callback_url"),
        ("projects", "0014_flowstart_contactgroupflowreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowstart",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flowstarts",
                to="rooms.room",
                verbose_name="room",
            ),
        ),
        migrations.AlterField(
            model_name="flowstart",
            name="permission",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flowstarts",
                to="projects.projectpermission",
                verbose_name="Permission",
            ),
        ),
    ]
