# Generated by Django 4.1.2 on 2023-04-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_flowstart_room_alter_flowstart_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowstart",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="is deleted?"),
        ),
    ]
