# Generated by Django 4.1.2 on 2023-08-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_flowstart_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="config",
            field=models.JSONField(blank=True, null=True, verbose_name="config"),
        ),
    ]
