# Generated by Django 4.1.2 on 2024-10-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_flowstart_contact_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="org",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="org uuid"
            ),
        ),
    ]
