# Generated by Django 4.1.2 on 2025-01-31 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_project_org"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_statuses",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "project")},
            },
        ),
    ]
