# Generated by Django 4.1.2 on 2025-02-11 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_customstatus_created_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customstatus",
            name="id",
        ),
        migrations.AddField(
            model_name="customstatus",
            name="modified_on",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified on"),
        ),
        migrations.AddField(
            model_name="customstatus",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="customstatus",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
        ),
    ]
