# Generated by Django 4.1.2 on 2025-02-28 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_alter_customstatus_break_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="customstatus",
            name="project",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
        ),
        migrations.AddConstraint(
            model_name="customstatus",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("user", "project"),
                name="unique_active_custom_status_per_user_project",
            ),
        ),
    ]
