# Generated by Django 4.1.2 on 2025-03-19 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0023_customstatus_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customstatustype",
            name="config",
            field=models.JSONField(blank=True, null=True, verbose_name="config"),
        ),
        migrations.AlterField(
            model_name="customstatus",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
        ),
    ]
