# Generated by Django 4.1.2 on 2025-03-10 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0024_alter_customstatus_project_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="customstatustype",
            unique_together=set(),
        ),
    ]
