# Generated by Django 4.1.2 on 2025-03-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0025_alter_customstatustype_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="customstatustype",
            name="config",
            field=models.JSONField(blank=True, null=True, verbose_name="config"),
        ),
    ]
