# Generated by Django 4.1.2 on 2025-04-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0025_alter_customstatustype_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectpermission",
            name="last_seen_online",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last seen online"
            ),
        ),
    ]
