# Generated by Django 4.1.2 on 2025-06-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0026_project_room_routing_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customstatustype",
            name="config",
            field=models.JSONField(blank=True, null=True, verbose_name="config"),
        ),
    ]
