# Generated by Django 4.1.2 on 2025-04-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0026_customstatustype_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="room_routing_type",
            field=models.CharField(
                blank=True,
                choices=[("GENERAL", "General"), ("QUEUE_PRIORITY", "Queue Priority")],
                default="GENERAL",
                help_text="Whether to route rooms using the queue priority or general routing",
                max_length=50,
                null=True,
                verbose_name="Room routing type",
            ),
        ),
    ]
