# Generated by Django 4.1.2 on 2025-07-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0027_customstatustype_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="room_routing_type",
            field=models.CharField(
                blank=True,
                choices=[("GENERAL", "General"), ("QUEUE_PRIORITY", "Queue Priority")],
                default="QUEUE_PRIORITY",
                help_text="Whether to route rooms using the queue priority or general routing",
                max_length=50,
                null=True,
                verbose_name="Room routing type",
            ),
        ),
    ]
