# Generated by Django 4.1.2 on 2025-07-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0029_change_projects_room_routing_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="internal_flags",
            field=models.JSONField(
                default=dict,
                help_text="Internal flags for the project",
                verbose_name="Internal flags",
            ),
        ),
    ]
