# Generated by Django 4.0.4 on 2025-09-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0031_agentdisconnectlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_csat_enabled",
            field=models.BooleanField(default=False, verbose_name="is CSAT enabled?"),
        ),
    ]
