# Generated by Django 4.0.4 on 2025-09-15 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0030_project_internal_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDisconnectLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_disconnected_logs', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='agent')),
                ('disconnected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_disconnect_actions', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='disconnected by')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_disconnect_logs', to='projects.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'Agent Disconnect Log',
                'verbose_name_plural': 'Agent Disconnect Logs',
            },
        ),
    ]
