# Generated by Django 4.0.4 on 2025-10-06 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_project_is_csat_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_csat_enabled',
        ),
    ]
