# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_agentstatuslog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpermission',
            name='last_seen',
            field=models.DateTimeField(
                blank=True,
                help_text='Last time the agent sent a ping (heartbeat)',
                null=True,
                verbose_name='Last seen',
            ),
        ),
    ]
