# Generated by Django 4.0.4 on 2026-03-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_projectpermission_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpermission',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is deleted?'),
        ),
    ]
