# Generated by Django 4.0.4 on 2025-10-16 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0032_remove_project_is_csat_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentStatusLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('log_date', models.DateField(help_text="Date of the log (agent's local timezone)", verbose_name='log date')),
                ('status_changes', models.JSONField(default=list, help_text="List of status change events: [{'timestamp': '...', 'status': 'ONLINE|OFFLINE', 'custom_status': 'status_name or null', 'status_type_uuid': '...'}]", verbose_name='status changes')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_status_logs', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='agent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_status_logs', to='projects.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'Agent Status Log',
                'verbose_name_plural': 'Agent Status Logs',
            },
        ),
        migrations.AddIndex(
            model_name='agentstatuslog',
            index=models.Index(fields=['agent', 'project', 'log_date'], name='projects_ag_agent_i_22caaa_idx'),
        ),
        migrations.AddIndex(
            model_name='agentstatuslog',
            index=models.Index(fields=['project', 'log_date'], name='projects_ag_project_a9686b_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentstatuslog',
            constraint=models.UniqueConstraint(fields=('agent', 'project', 'log_date'), name='unique_agent_project_date_log'),
        ),
    ]
