# Generated by Django 4.0.4 on 2026-04-07 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0033_projectpermission_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model name')),
                ('object_uuid', models.UUIDField(verbose_name='Object UUID')),
                ('object_repr', models.CharField(max_length=255, verbose_name='Object description')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_logs', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_logs', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Deletion log',
                'verbose_name_plural': 'Deletion logs',
                'ordering': ['-created_on'],
            },
        ),
    ]
