# Generated by Django 4.0.4 on 2026-04-08 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_deletionlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeletionLog',
        ),
    ]
