# Generated by Django 4.2.23 on 2026-09-24 17:57

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0037_project_is_live_desk_copilot"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnifiedSacMigration",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="Modified on"),
                ),
                (
                    "org",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="org uuid"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SETTING_PRINCIPAL", "Setting Principal"),
                            ("PRINCIPAL_SET", "Principal Set"),
                            ("CLOSING_ROOMS", "Closing Rooms"),
                            ("ROOMS_CLOSED", "Rooms Closed"),
                            ("DELETING_QUEUES", "Deleting Queues"),
                            ("QUEUES_DELETED", "Queues Deleted"),
                            ("DELETING_SECTORS", "Deleting Sectors"),
                            ("SECTORS_DELETED", "Sectors Deleted"),
                            ("FINISHED", "Finished"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=32,
                        verbose_name="status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started at"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finished at"
                    ),
                ),
                ("error", models.JSONField(blank=True, null=True, verbose_name="error")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unified_sac_migrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "principal_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unified_sac_migrations",
                        to="projects.project",
                        verbose_name="Principal project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unified SAC migration",
                "verbose_name_plural": "Unified SAC migrations",
            },
        ),
        migrations.AddConstraint(
            model_name="unifiedsacmigration",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["FINISHED", "FAILED"]), _negated=True
                ),
                fields=("org",),
                name="unique_in_progress_unified_sac_migration_per_org",
            ),
        ),
    ]
