# Generated by Django 4.0.4 on 2026-05-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0037_projectpermission_chats_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_chats_summary_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Whether to enable the chats summary feature for this project",
                verbose_name="Is chats summary enabled?",
            ),
        ),
    ]
