# Generated by Django 4.0.4 on 2026-07-02 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0038_project_is_chats_summary_enabled"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agentstatuslog",
            options={
                "verbose_name": "Representative status log",
                "verbose_name_plural": "Representative status logs",
            },
        ),
        migrations.AlterModelOptions(
            name="contactgroupflowreference",
            options={
                "verbose_name": "Flow contact/group reference",
                "verbose_name_plural": "Flow contact/group references",
            },
        ),
        migrations.AlterModelOptions(
            name="flowstart",
            options={
                "verbose_name": "Flow start",
                "verbose_name_plural": "Flow starts",
            },
        ),
        migrations.AlterModelOptions(
            name="linkcontact",
            options={
                "verbose_name": "Linked contact",
                "verbose_name_plural": "Linked contacts",
            },
        ),
        migrations.AlterModelOptions(
            name="projectpermission",
            options={
                "verbose_name": "Project permission",
                "verbose_name_plural": "Project permissions",
            },
        ),
        migrations.AlterField(
            model_name="agentdisconnectlog",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_disconnected_logs",
                to=settings.AUTH_USER_MODEL,
                to_field="email",
                verbose_name="Representative",
            ),
        ),
        migrations.AlterField(
            model_name="agentdisconnectlog",
            name="disconnected_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_disconnect_actions",
                to=settings.AUTH_USER_MODEL,
                to_field="email",
                verbose_name="Disconnected by",
            ),
        ),
        migrations.AlterField(
            model_name="agentdisconnectlog",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_disconnect_logs",
                to="projects.project",
                verbose_name="Project",
            ),
        ),
        migrations.AlterField(
            model_name="agentstatuslog",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_status_logs",
                to=settings.AUTH_USER_MODEL,
                to_field="email",
                verbose_name="Representative",
            ),
        ),
        migrations.AlterField(
            model_name="agentstatuslog",
            name="log_date",
            field=models.DateField(
                help_text="Log date (representative's local timezone)",
                verbose_name="Log date",
            ),
        ),
        migrations.AlterField(
            model_name="agentstatuslog",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_status_logs",
                to="projects.project",
                verbose_name="Project",
            ),
        ),
        migrations.AlterField(
            model_name="agentstatuslog",
            name="status_changes",
            field=models.JSONField(
                default=list,
                help_text="List of status change events: [{'timestamp': '...', 'status': 'ONLINE|OFFLINE', 'custom_status': 'status_name or null', 'status_type_uuid': '...'}]",
                verbose_name="Status changes",
            ),
        ),
        migrations.AlterField(
            model_name="contactgroupflowreference",
            name="flow_start",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="references",
                to="projects.flowstart",
                verbose_name="Flow start",
            ),
        ),
        migrations.AlterField(
            model_name="contactgroupflowreference",
            name="receiver_type",
            field=models.CharField(max_length=50, verbose_name="Receiver type"),
        ),
        migrations.AlterField(
            model_name="customstatus",
            name="break_time",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Custom status timing"
            ),
        ),
        migrations.AlterField(
            model_name="flowstart",
            name="flow",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Flow ID"
            ),
        ),
        migrations.AlterField(
            model_name="flowstart",
            name="name",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Flow name"
            ),
        ),
        migrations.AlterField(
            model_name="linkcontact",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_contacts",
                to="projects.project",
                verbose_name="Project",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="date_format",
            field=models.CharField(
                choices=[("D", "DD-MM-YYYY"), ("M", "MM-DD-YYYY")],
                default="D",
                help_text="Choose whether dates show the day or month first",
                max_length=1,
                verbose_name="Date format",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="flows_authorization",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Flows authorization token",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="project",
            name="room_routing_type",
            field=models.CharField(
                blank=True,
                choices=[("GENERAL", "General"), ("QUEUE_PRIORITY", "Queue Priority")],
                default="QUEUE_PRIORITY",
                help_text="Choose whether to route rooms based on queue priority or general routing",
                max_length=50,
                null=True,
                verbose_name="Room routing type",
            ),
        ),
        migrations.AlterField(
            model_name="projectpermission",
            name="first_access",
            field=models.BooleanField(
                default=True, verbose_name="Is this the user's first access?"
            ),
        ),
        migrations.AlterField(
            model_name="projectpermission",
            name="role",
            field=models.PositiveIntegerField(
                choices=[(0, "not set"), (1, "admin"), (2, "Representative")],
                default=0,
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="projectpermission",
            name="status",
            field=models.CharField(
                choices=[
                    ("ONLINE", "online"),
                    ("OFFLINE", "offline"),
                    ("AWAY", "away"),
                    ("BUSY", "busy"),
                ],
                default="OFFLINE",
                max_length=10,
                verbose_name="User status",
            ),
        ),
        migrations.AlterField(
            model_name="templatetype",
            name="setup",
            field=models.JSONField(default=dict, verbose_name="Template setup"),
        ),
    ]
