# Generated by Django 4.0.4 on 2026-09-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0039_alter_agentstatuslog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_live_desk_copilot",
            field=models.BooleanField(
                default=False,
                help_text="Whether this project is a Live Desk copilot project",
                verbose_name="Is Live Desk copilot?",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="parent_project_uuid",
            field=models.UUIDField(
                blank=True,
                help_text="UUID of the Live Desk project this copilot belongs to",
                null=True,
                verbose_name="Parent project UUID",
            ),
        ),
    ]
