# Generated by Django 4.0.4 on 2026-05-20 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussionmessagemedia',
            options={'verbose_name': 'Discussion message media', 'verbose_name_plural': 'Discussion message media'},
        ),
        migrations.AlterField(
            model_name='discussion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='Subject text'),
        ),
        migrations.AlterField(
            model_name='discussionmessagemedia',
            name='content_type',
            field=models.CharField(max_length=300, verbose_name='Content type'),
        ),
        migrations.AlterField(
            model_name='discussionmessagemedia',
            name='media_file',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='discussionmedia/%Y/%m/%d/', verbose_name='Media file'),
        ),
    ]
