# Generated by Django 4.1.2 on 2023-10-30 19:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscussionMessageMedia",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="Modified on"),
                ),
                (
                    "content_type",
                    models.CharField(max_length=300, verbose_name="Content Type"),
                ),
                (
                    "media_file",
                    models.FileField(
                        blank=True,
                        max_length=300,
                        null=True,
                        upload_to="",
                        verbose_name="Media File",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussion_medias",
                        to="discussions.discussionmessage",
                        verbose_name="discussion message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discussion Message Media",
                "verbose_name_plural": "Discussion Message Medias",
            },
        ),
    ]
