# Generated by Django 4.1.2 on 2023-10-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="discussion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("room",),
                name="unique_room_is_activetrue_room",
            ),
        ),
    ]
