# Generated by Django 4.1.2 on 2023-11-09 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "discussions",
            "0003_remove_discussion_unique_room_is_activetrue_room_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="discussionmessagemedia",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medias",
                to="discussions.discussionmessage",
                verbose_name="discussion message",
            ),
        ),
    ]
