# Generated by Django 4.1.2 on 2023-11-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0004_alter_discussionmessagemedia_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discussionmessagemedia",
            name="media_file",
            field=models.FileField(
                blank=True,
                max_length=300,
                null=True,
                upload_to="discussionmedia/%Y/%m/%d/",
                verbose_name="Media File",
            ),
        ),
    ]
