# Generated by Django 4.0.5 on 2022-08-15 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='sector name')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_authorizations', to='sectors.sector', to_field='uuid', verbose_name='queues')),
            ],
            options={
                'verbose_name': 'Sector Queue',
                'verbose_name_plural': 'Sector Queues',
            },
        ),
        migrations.CreateModel(
            name='QueueAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('role', models.PositiveIntegerField(choices=[(0, 'not set'), (1, 'agent')], default=1, verbose_name='role')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='queues.queue', to_field='uuid', verbose_name='Queue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_authorizations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Sector Queue Authorization',
                'verbose_name_plural': 'Sector Queues Authorization',
            },
        ),
    ]
