# Generated by Django 4.0.5 on 2022-08-23 13:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectors', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Name')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='sectors.sector', verbose_name='sector')),
            ],
            options={
                'verbose_name': 'Sector Queue',
                'verbose_name_plural': 'Sector Queues',
            },
        ),
        migrations.CreateModel(
            name='QueueAuthorization',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('role', models.PositiveIntegerField(choices=[(0, 'not set'), (1, 'agent')], default=1, verbose_name='role')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_authorizations', to='projects.projectpermission', verbose_name='User')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='queues.queue', verbose_name='Queue')),
            ],
            options={
                'verbose_name': 'Sector Queue Authorization',
                'verbose_name_plural': 'Sector Queues Authorization',
            },
        ),
    ]
