# Generated by Django 4.0.5 on 2022-09-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='queue',
            constraint=models.UniqueConstraint(fields=('sector', 'name'), name='unique_queue_name'),
        ),
        migrations.AddConstraint(
            model_name='queueauthorization',
            constraint=models.UniqueConstraint(fields=('queue', 'permission'), name='unique_queue_auth'),
        ),
    ]
