# Generated by Django 4.0.5 on 2022-08-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queueauthorization',
            old_name='user',
            new_name='permission',
        ),
    ]
