# Generated by Django 4.1.2 on 2023-04-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queues", "0002_queue_unique_queue_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="queue",
            name="default_message",
            field=models.TextField(
                blank=True, null=True, verbose_name="Default queue message"
            ),
        ),
    ]
