# Generated by Django 4.1.2 on 2023-04-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queues", "0002_queue_unique_queue_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="queue",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="is active?"),
        ),
    ]
