# Generated by Django 4.1.2 on 2023-04-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queues", "0003_queue_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queue",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="is deleted?"),
        ),
    ]
