# Generated by Django 4.1.2 on 2023-08-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queues", "0004_queue_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="queue",
            name="config",
            field=models.JSONField(blank=True, null=True, verbose_name="config"),
        ),
    ]
