# Generated by Django 4.0.4 on 2026-02-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0005_queue_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='is_limit_active',
            field=models.BooleanField(default=False, verbose_name='Is limit active?'),
        ),
    ]
