# Generated by Django 4.0.4 on 2026-05-20 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0025_alter_groupsector_options_and_more'),
        ('queues', '0007_queue_created_by_queue_deleted_by_queue_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'verbose_name': 'Department queue', 'verbose_name_plural': 'Department queues'},
        ),
        migrations.AlterModelOptions(
            name='queueauthorization',
            options={'verbose_name': 'Department queue authorization', 'verbose_name_plural': 'Department queue authorizations'},
        ),
        migrations.AlterField(
            model_name='queue',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='sectors.sector', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='queueauthorization',
            name='role',
            field=models.PositiveIntegerField(choices=[(0, 'not set'), (1, 'Representative')], default=1, verbose_name='role'),
        ),
    ]
