# Generated by Django 4.0.4 on 2026-06-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0007_queue_created_by_queue_deleted_by_queue_modified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueauthorization',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is deleted?'),
        ),
    ]
