# Generated by Django 4.0.4 on 2026-07-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0008_queueauthorization_is_deleted'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='queueauthorization',
            name='unique_queue_auth',
        ),
        migrations.AddConstraint(
            model_name='queueauthorization',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('queue', 'permission'), name='unique_queue_auth'),
        ),
    ]
