# Generated by Django 4.0.4 on 2026-07-02 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0028_alter_groupsector_options_and_more'),
        ('queues', '0008_queueauthorization_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'verbose_name': 'Department queue', 'verbose_name_plural': 'Department queues'},
        ),
        migrations.AlterModelOptions(
            name='queueauthorization',
            options={'verbose_name': 'Department queue authorization', 'verbose_name_plural': 'Department queue authorizations'},
        ),
        migrations.AlterField(
            model_name='queue',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='sectors.sector', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='queueauthorization',
            name='role',
            field=models.PositiveIntegerField(choices=[(0, 'not set'), (1, 'Representative')], default=1, verbose_name='role'),
        ),
    ]
