# Generated by Django 4.0.4 on 2026-07-08 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "queues",
            "0010_alter_queue_options_alter_queueauthorization_options_and_more",
        ),
    ]

    operations = []
